/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdLocationListRelationFilter } from "../../adLocation/base/AdLocationListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { AdSpendListRelationFilter } from "../../adSpend/base/AdSpendListRelationFilter";
import { BusinessCryptoListRelationFilter } from "../../businessCrypto/base/BusinessCryptoListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";

@InputType()
class AdvertiserWhereInput {
  @ApiProperty({
    required: false,
    type: () => AdLocationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AdLocationListRelationFilter)
  @IsOptional()
  @Field(() => AdLocationListRelationFilter, {
    nullable: true,
  })
  adLocations?: AdLocationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AdSpendListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AdSpendListRelationFilter)
  @IsOptional()
  @Field(() => AdSpendListRelationFilter, {
    nullable: true,
  })
  adSpends?: AdSpendListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => BusinessCryptoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BusinessCryptoListRelationFilter)
  @IsOptional()
  @Field(() => BusinessCryptoListRelationFilter, {
    nullable: true,
  })
  businessCryptos?: BusinessCryptoListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;
}

export { AdvertiserWhereInput as AdvertiserWhereInput };
